const Data = [
    {
        trekId : '1',
        trekName : 'Trek to Lonavala',
        trekDescription : 'One Day weekend short trip',
        trekDifficultylevel : 'Easy',
        trekFacts : 'Lonavala is a hill station surrounded by green valleys in western India near Mumbai. The Karla Caves and the Bhaja Caves are ancient Buddhist shrines carved out of the rock. They feature massive pillars and intricate relief sculptures.',
        trekDuration : '1 Day',
        trekStartDate: '5-Jan-2019',
        trekEndDate: '5-Jan-2019',
        trekCharges: '1000',
        campLeader: 'Satish Khobragade', 
        campLeaderDeatils : 'Trekking experience of 15 Years',
        gallery:''
    }, 
    {
        trekId : '2',
        trekName : 'Trek to Vasota',
        trekDescription : '2 Days weekend Trip',
        trekDifficultylevel : 'Hard',
        trekFacts : 'Vasota Fort is located in Satara district in the Indian state of Maharashtra.',
        trekDuration : '2 Days',
        trekStartDate: '10-Jan-2019',
        trekEndDate: '11-Jan-2019',
        trekCharges: '1500',
        campLeader: 'Parth Dubal', 
        campLeaderDeatils : 'Trekking experience of 5 Years',
        gallery:''
    },
    {
        trekId : '3',
        trekName : 'Trek to Tapola',
        trekDescription : 'Stay near to the river in tent',
        trekDifficultylevel : 'Medium',
        trekFacts : ' Situated about 147 kilometres from Pune, Tapola is a quaint hamlet at Mahabaleshwar, known for its breathtaking scenic beauty',
        trekDuration : '2 days',
        trekStartDate: '15-Jan-2019',
        trekEndDate: '16-Jan-2019',
        trekCharges: '3000',
        campLeader: 'Sneh Kumar Bhansali', 
        campLeaderDeatils : 'Trekking experience of 1 Years',
        gallery:''
    },
    {
        trekId : '4',
        trekName : 'Trek to Rajgarh',
        trekDescription : 'Stay near to the river in tent',
        trekDifficultylevel : 'Medium',
        trekFacts : ' Situated about 147 kilometres from Pune, Tapola is a quaint hamlet at Mahabaleshwar, known for its breathtaking scenic beauty',
        trekDuration : '2 days',
        trekStartDate: '15-Jan-2019',
        trekEndDate: '16-Jan-2019',
        trekCharges: '3000',
        campLeader: 'Sneh Kumar Bhansali', 
        campLeaderDeatils : 'Trekking experience of 1 Years',
        gallery:''
    },
    {
        trekId : '5',
        trekName : 'Trek to Kalsubai',
        trekDescription : 'Stay near to the river in tent',
        trekDifficultylevel : 'Medium',
        trekFacts : ' Situated about 147 kilometres from Pune, Tapola is a quaint hamlet at Mahabaleshwar, known for its breathtaking scenic beauty',
        trekDuration : '2 days',
        trekStartDate: '15-Jan-2019',
        trekEndDate: '16-Jan-2019',
        trekCharges: '3000',
        campLeader: 'Sneh Kumar Bhansali', 
        campLeaderDeatils : 'Trekking experience of 1 Years',
        gallery:''
    },
    {
        trekId : '6',
        trekName : 'Trek to Kasarsai',
        trekDescription : 'Stay near to the river in tent',
        trekDifficultylevel : 'Medium',
        trekFacts : ' Situated about 147 kilometres from Pune, Tapola is a quaint hamlet at Mahabaleshwar, known for its breathtaking scenic beauty',
        trekDuration : '2 days',
        trekStartDate: '15-Jan-2019',
        trekEndDate: '16-Jan-2019',
        trekCharges: '3000',
        campLeader: 'Sneh Kumar Bhansali', 
        campLeaderDeatils : 'Trekking experience of 1 Years',
        gallery:''
    },
    {
        trekId : '7',
        trekName : 'Trek to DevKund',
        trekDescription : 'Stay near to the river in tent',
        trekDifficultylevel : 'Medium',
        trekFacts : ' Situated about 147 kilometres from Pune, Tapola is a quaint hamlet at Mahabaleshwar, known for its breathtaking scenic beauty',
        trekDuration : '2 days',
        trekStartDate: '15-Jan-2019',
        trekEndDate: '16-Jan-2019',
        trekCharges: '3000',
        campLeader: 'Sneh Kumar Bhansali', 
        campLeaderDeatils : 'Trekking experience of 1 Years',
        gallery:''
    },
    {
        trekId : '8',
        trekName : 'Trek to Khadakvasla',
        trekDescription : 'Stay near to the river in tent',
        trekDifficultylevel : 'Medium',
        trekFacts : ' Situated about 147 kilometres from Pune, Tapola is a quaint hamlet at Mahabaleshwar, known for its breathtaking scenic beauty',
        trekDuration : '2 days',
        trekStartDate: '15-Jan-2019',
        trekEndDate: '16-Jan-2019',
        trekCharges: '3000',
        campLeader: 'Sneh Kumar Bhansali', 
        campLeaderDeatils : 'Trekking experience of 1 Years',
        gallery:''
    },
    {
        trekId : '9',
        trekName : 'Trek to Sinhagarh Fort',
        trekDescription : 'Stay near to the river in tent',
        trekDifficultylevel : 'Medium',
        trekFacts : ' Situated about 147 kilometres from Pune, Tapola is a quaint hamlet at Mahabaleshwar, known for its breathtaking scenic beauty',
        trekDuration : '2 days',
        trekStartDate: '15-Jan-2019',
        trekEndDate: '16-Jan-2019',
        trekCharges: '3000',
        campLeader: 'Sneh Kumar Bhansali', 
        campLeaderDeatils : 'Trekking experience of 1 Years',
        gallery:''
    },
    {
        trekId : '10',
        trekName : 'Trek to ShivNeri Fort',
        trekDescription : 'Stay near to the river in tent',
        trekDifficultylevel : 'Medium',
        trekFacts : ' Situated about 147 kilometres from Pune, Tapola is a quaint hamlet at Mahabaleshwar, known for its breathtaking scenic beauty',
        trekDuration : '2 days',
        trekStartDate: '15-Jan-2019',
        trekEndDate: '16-Jan-2019',
        trekCharges: '3000',
        campLeader: 'Sneh Kumar Bhansali', 
        campLeaderDeatils : 'Trekking experience of 1 Years',
        gallery:''
    },
    {
        trekId : '11',
        trekName : 'Trek to Kamshet',
        trekDescription : 'Stay near to the river in tent',
        trekDifficultylevel : 'Medium',
        trekFacts : ' Situated about 147 kilometres from Pune, Tapola is a quaint hamlet at Mahabaleshwar, known for its breathtaking scenic beauty',
        trekDuration : '2 days',
        trekStartDate: '15-Jan-2019',
        trekEndDate: '16-Jan-2019',
        trekCharges: '3000',
        campLeader: 'Sneh Kumar Bhansali', 
        campLeaderDeatils : 'Trekking experience of 1 Years',
        gallery:''
    },
]

export default Data